services:
  relayer:
    image: ghcr.io/sprintertech/sprinter-signing:${SIGNING_IMAGE_VERSION}
    command: run --config /cfg/config.json
    volumes:
      - ./cfg:/cfg
    labels:
      logging: "alloy"
      logging_jobname: "containerlogs"
      service_name: "${SERVICE_NAME}"
    ports:
      - "${API_PORT:-3000}:3000"
      - "${P2P_PORT:-9000}:9000"
    restart: always
